config/routes.rb
Rails.application.routes.draw do
  get 'doctor/show'
  get 'doctor/schedule'
  post 'doctor/schedule'
  get'doctor/index'
  get'doctor/patient_view/:id', to: 'doctor#patient_view', as:'doctor_patient_view'
  get 'patient/show', to: 'patient#show' #=> 'users/registrations#after_sign_up_path_for'
  get 'patient/schedule'
  get'patient/index'
  get'patient/doctor_view/:id', to: 'patient#doctor_view', as: 'patient_doctor_view'

  devise_for :users, controllers: { sessions: 'users/sessions',registrations: "users/registrations" }, path: '',path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  #devise_for :users
  resources :forums, except: :index
  root'forums#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :diseases
  has_many :medicines
  belongs_to :user
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
  def show
    @user = current_user
  end
  def index
    @patients =  Relation.where(:doctor_id =>Doctor.where(:user_id => current_user))
  end
def doctor_view
  @patient=  User.find(params[:id])
end
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/patient/doctor_view.html.erb
<h1>account info </h1>
<%=image_tag (@patient.img)%>
</br>
<%=@patient.account_type%>
</br>
<%=@patient.email%>
</br>
<%=@patient.encrypted_password%>
</br>
<%=@patient.patient.id%>
</br>
<%=current_user.id%>

app/views/patient/index.html.erb
<% @patients.each do |pat|%>
<%=pat.inspect%>
<%= link_to "show",patient_doctor_view_path(@params,:id => pat.id)%>
<%end%>
<%=current_user.id%>

app/views/patient/show.html.erb
<h1>account info </h1>
<%=image_tag (current_user.img)%>
</br>
<%=current_user.account_type%>
</br>
<%=current_user.email%>
</br>
<%=current_user.encrypted_password%>
</br>
<%=current_user.patient.id%>
</br>
<%=current_user.id%>
<h4>doctor's dealing with </h4>

<%= link_to "list of all doctors",doctor_index_path%> 