config/routes.rb
Rails.application.routes.draw do
  get 'doctor/show'
  get 'doctor/schedule'
  post 'doctor/schedule'
  get'doctor/index'
  get'doctor/patient_view/:id', to: 'doctor#patient_view', as:'doctor_patient_view'
  get 'patient/show', to: 'patient#show' #=> 'users/registrations#after_sign_up_path_for'
  get 'patient/schedule'
  get'patient/index'
  get'patient/doctor_view/:id', to: 'patient#doctor_view', as: 'patient_doctor_view'

  devise_for :users, controllers: { sessions: 'users/sessions',registrations: "users/registrations" }, path: '',path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  #devise_for :users
  resources :forums, except: :index
  root'forums#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user
end

app/controllers/doctor_controller.rb
class DoctorController < ApplicationController
  def show
    @user=current_user
  end
  def schedule
    @appointments_made = Appointment.new
    doc=Doctor.where(user_id: current_user.id)
    @confirmed_appointments = Appointment.where(:doctor_id => doc).where(confirmed: 'true')
    @unconfirmed_appointments = Appointment.where(confirmed: 'false' )

  end
  def index
    @doctors_available = User.where(account_type: 'doctor')

  end
  def patient_view
    @doctor=  User.find(params[:id])
  end

end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/views/doctor/index.html.erb
<% @doctors_available.each do |doc|%>
<%=doc.id%>
<%=doc.email%>
<%= link_to "show",doctor_patient_view_path(@params,:id => doc.id)%> 
<%end%>

app/views/doctor/patient_view.html.erb
<h1>account info </h1>
<%=image_tag (@doctor.img)%>
</br>
<%=@doctor.account_type%>
</br>
<%=@doctor.email%>
</br>
<%=@doctor.encrypted_password%>
</br>
<%=@doctor.doctor.id%>
</br>
<%=current_user.id%>

app/views/doctor/schedule.html.erb
<%= form_for :@appointments_made do |f| %>
<%=f.date_select (:day)%>
<%=f.select :start_time, (0..23)%>
<span>to:</span>
<%=f.select :end_time,(0..23)%>
</br>
<%= f.submit "make the appointment"%>
<% end %>

<ul>
<%@confirmed_appointments.each do|c|%>
<%=c.day %>
<%=c.start_time %>
<%=c.end_time%>
<%=c.patient_id%>
<%end%>
</ul>
<ul>
<%@unconfirmed_appointments.each do|n|%>
<%=n.day %>
<%=n.start_time %>
<%=n.end_time%>
<%=n.patient_id%>
<%end%>
</ul>

app/views/doctor/show.html.erb
<h1>account info </h1>
<%=image_tag (current_user.img)%>
</br>
<%=current_user.account_type%>
</br>
<%=current_user.email%>
</br>
<%=current_user.encrypted_password%>
</br>
<%=current_user.doctor.id%>
</br>
<%=current_user.id%>

<h4>patient's resposible for </h4>
</br>
<%= link_to "schedule", doctor_schedule_path%>
<%= link_to "see your patients", patient_index_path%>